# Generated by Django 3.1.6 on 2021-02-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram Id for user')),
                ('telegram_name', models.CharField(max_length=32, unique=True, verbose_name='Telegram id of user')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(verbose_name='Geo Request')),
                ('result', models.TextField(verbose_name='Result of request')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.telegramuser')),
            ],
        ),
    ]
